[package]
name = "rody"
version = "0.1.0"
authors = ["AlexandreImperiale <https://github.com/AlexandreImperiale>"]
description = "A rust crate for rigid body motion."

[dependencies]
mersh = { git = "https://github.com/AlexandreImperiale/mersh" }
